language: c
compiler:
  - clang
  - gcc
sudo: false
notifications:
  email:
    recipients:
      - travisci@benary.org
    on_success: change
    on_failure: always
before_script:
  - autoreconf --install
script: './configure && make && make check'
